version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: env_monitor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/env_monitor
      JWT_SECRET: your-jwt-secret-here
      NODE_ENV: production
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./apps/api:/app
    command: ["npm", "run", "dev"]

volumes:
  postgres_data: